### PR TITLE
Update: use pyopensprinkler 0.5.x

### LINKED ISSUE #53: Update pyopensprinkler to 0.5.0
Update pyopensprinkler to 0.5.0 when released: https://github.com/vinteo/py-opensprinkler/pull/12

### PR DESCRIPTION
**Pull request by vinteo**
Closes #53

### CODE REVIEW

**Comment by travisghansen** [comment]
Nice! Pretty excited about testing this bit out now.

**Comment by vinteo** [comment]
pip still can't install the new version yet, will have to wait a bit. Once this goes in we can go all out on the other issues!

**Comment by travisghansen** [comment]
Yeah does pip queue up or something?

**Comment by vinteo** [comment]
Not sure how it works but usually it takes an hour or more

**Comment by travisghansen** [comment]
Ah interesting. Odd that you don’t push to...is it synced with tags from github or something?

**Comment by vinteo** [comment]
I do push/upload it using twine, and it appears on the PyPi website instantly but pip takes a while. I suspect it takes a while to distribute it to the pip servers

**Comment by travisghansen** [comment]
Ah I see.

**Comment by vinteo** [comment]
Seems to be taking longer than usual. Can't see any issues: https://pypi.org/project/pyopensprinkler/

**Comment by travisghansen** [comment]
Comes up with 0.5.0 for me. Does it just not download when you install the deps?

**Comment by vinteo** [comment]
Yea it says not found

**Comment by travisghansen** [comment]
Hmm, I’ll try in a bit and let you know what I get.

**Comment by travisghansen** [comment]
```
pip install pyopensprinkler
Collecting pyopensprinkler
  Downloading pyopensprinkler-0.5.1.tar.gz (7.0 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting httplib2==0.18.1
  Using cached httplib2-0.18.1-py3-none-any.whl (95 kB)
Collecting backoff==1.10.0
  Using cached backoff-1.10.0-py2.py3-none-any.whl (31 kB)
Building wheels for collected packages: pyopensprinkler
  Building wheel for pyopensprinkler (PEP 517) ... done
  Created wheel for pyopensprinkler: filename=pyopensprinkler-0.5.1-py3-none-any.whl size=6979 sha256=d930fce240d4cf3e6dc025c6be2a3e82ec7ae3beb4b72544b8e5e1d3eefeff34
  Stored in directory: /home/thansen/.cache/pip/wheels/e1/b1/58/ebec8a1712122a242d77a17fbea4b0894c699511fc51e3e775
Successfully built pyopensprinkler
Installing collected packages: httplib2, backoff, pyopensprinkler
Successfully installed backoff-1.10.0 httplib2-0.18.1 pyopensprinkler-0.5.1

```

**Comment by vinteo** [comment]
Yea looks like it was me environment for some reason

**Comment by travisghansen** [comment]
Ok cool. Let’s get it merged and have some fun :)

**Comment by vinteo** [comment]
OK I got it to a working state. Please review and quick test if possible (esp the SSL option). If OK then good to merge

**Comment by travisghansen** [comment]
This is going to the new branch still right? I’ve got a few things but we can probably iterate after it’s merged.

**Comment by vinteo** [comment]
yup going into the feature branch

**Comment by travisghansen** [comment]
Ok I say merge it and we’ll go from there. I can test it out shortly.

**Pull request merged**
