### PR TITLE
New: services to run programs and run/stop stations

### LINKED ISSUE #59: Add service to run program

### LINKED ISSUE #60: Add service to run and stop stations
Should accept a run duration

### PR DESCRIPTION
**Pull request by vinteo**
Closes #59 
Closes #60 

To test:

Developer Tools -> Services

Services available: `opensprinkler.run_program`, `opensprinkler.run_station`, `opensprinkler.stop_station`

### CODE REVIEW

**Comment by vinteo** [comment]
Dev docs for services: https://developers.home-assistant.io/docs/dev_101_services

**Comment by vinteo** [comment]
With this PR I think we have equivalent features of what there is currently

**Comment by travisghansen** [comment]
Should the services for `stations` be on the `switch` as well instead of the sensor?

**Comment by vinteo** [comment]
Updated to put them on the stations

**Comment by travisghansen** [comment]
I don't really know the answer to be honest. Seems good for consistency but I could see an argument for saying the actions have the ability to change the state of the sensor vs the switch and therefore make more sense on the sensor..

**Comment by vinteo** [comment]
Well actually we can put them on both and the same service can use either. I will put it on the sensor as well

**Comment by travisghansen** [comment]
lol was just thinking that myself. Same for `binary_sensor`s. Just so long as we keep the attribute the same across all of them then it should be good.

**Comment by travisghansen** [comment]
The attribute of the object that is.

**Comment by travisghansen** [comment]
Anything else on this one or ready to merge?

**Comment by vinteo** [comment]
Ok added it back to sensors, this should be ready now

**Pull request merged**
