### PR TITLE
fix: make run_seconds in service optional

### PR DESCRIPTION
**Pull request by vinteo**

### CODE REVIEW

**Comment by Nick-Adams-AU** [comment]
I think this still needs a default run_seconds as pyopensprinkler won't provide one.

**Comment by travisghansen** [comment]
@Nick-Adams-AU `pyopensprinkler` defaults to 60 seconds.

**Comment by vinteo** [comment]
Here: https://github.com/vinteo/py-opensprinkler/blob/master/pyopensprinkler/station.py#L65

I tested it so it does work

**Comment by travisghansen** [comment]
@vinteo FYI I just hacked that method to default to `None` to prevent the crazy python behavior as an FYI.

**Pull request merged**
