### PR TITLE
Addresses issue #304 deprecated_has_helpers_service

### PR DESCRIPTION
**Pull request by cayossarian**
Changes call to entity_service_call to pass the hass as the first parameter and imports the proper package.

### CODE REVIEW

**Review by EdLeckert — APPROVED** [review]
Linter doesn't like the blank line at line 17, but other than that it seems fine.

**Comment by cayossarian** [comment]
> Linter doesn't like the blank line at line 17, but other than that it seems fine.
Thanks, I'll remove the line but I think the lint error is related to an import sort that was not part of my change.  If removing the line doesn't work I'll change the import sort:
PYTHON_ISORT
  2024-08-20 06:32:52 [INFO]   Linting PYTHON_ISORT items...
  Error: -20 06:32:53 [ERROR]   Found errors when linting PYTHON_ISORT. Exit code: 1.
  2024-08-20 06:32:53 [INFO]   Command output for PYTHON_ISORT:

**Review by vinteo — APPROVED** [review]

**Comment by vinteo** [comment]
thank you!

**Comment by cayossarian** [comment]
Thanks, @EdLeckert , yes clearly I read the diff wrong.  thanks for your help!

**Pull request merged**
