### PR TITLE
feat: continue_running_stations flag for run once program service

### PR DESCRIPTION
**Pull request by vinteo**
Fixes: #104

### CODE REVIEW

**Comment by vinteo** [comment]
@travisghansen flipped the flag around

**Comment by travisghansen** [comment]
Is there a reason this is only supported with the key/value syntax?

**Comment by vinteo** [comment]
You have to pad it in an array so a 0 is given. I don't think it's right to
over write that but that's just me

**Comment by travisghansen** [comment]
Not sure I follow that last comment. I understand the padding the array but what’s getting overwritten?

**Comment by vinteo** [comment]
for example if you want to run station 1 and 3 you have to provide [0, 60, 0, 60], I don't think its right to overwrite the `0` of stations 0 and 2, even with the flag. If the key/value way they still provide a 0 to station 2 to force stop it with the flag and keep station running. 

For example is 0 and 2 is running, they can do
```yaml
run_seconds:
  1: 60
  2: 0
  3: 30
continue_running_stations: True
```
to keep station 0 running but force station 2 to stop.

**Comment by travisghansen** [comment]
Oh right. I was thinking about doing run once on the station for some reason and got my wires crossed. I agree with your assessment, merge away!

This is a great feature add for sure.

**Comment by vinteo** [comment]
Merging...

**Pull request merged**
