### PR TITLE
New Service: Set water level

### PR DESCRIPTION
**Pull request by functionpointer**
Adds a new service that can set the water level for an OpenSprinkler in percent.

Fixes https://github.com/vinteo/hass-opensprinkler/issues/101

### CODE REVIEW

**Comment by vinteo** [comment]
Hi, this looks good, thank you. Could you just fix the minor linting error.

**Comment by vinteo** [comment]
Oh sorry, one more thing, could you add something in the readme for this service

**Review by vinteo — APPROVED** [review]

**Comment by functionpointer** [comment]
Not sure what to make of the final remaining linter warning:
```Error:  <Validation hacsjson> failed:  extra keys not allowed @ data['domains'] (More info: https://hacs.xyz/docs/publish/include#check-hacs-manifest )```

I didn't modify `hacs.json`. It doesn't show up in the [documentation](https://hacs.xyz/docs/publish/start) anymore. Maybe that key was removed?

**Comment by vinteo** [comment]
Looks like it was, could I trouble you to remove it as well in the PR

**Comment by vinteo** [comment]
thank you!

**Pull request merged**
